# Generated by Django 2.2.1 on 2019-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_retraining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='soul',
            field=models.CharField(blank=True, max_length=200, verbose_name='Душа)))))))'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='soul_key',
            field=models.CharField(blank=True, max_length=4, verbose_name='ключ от души'),
        ),
    ]
